package com.sharding.demo.dao;

import com.sharding.demo.bean.Detail;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface DetailMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail01
     *
     * @mbg.generated Mon Nov 05 16:16:19 CST 2018
     */
    int insert(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail01
     *
     * @mbg.generated Mon Nov 05 16:16:19 CST 2018
     */
    int insertSelective(Detail record);

    Detail selectDetailByDetailId(Map<String, Object> map);
//    Detail selectDetailByDetailId(Detail detail);


    int insertDetail(Map<String, Object> map);


}