package com.sharding.demo.bean;

public class TransFlow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_flow01.trans_id
     *
     * @mbg.generated Mon Nov 05 16:16:19 CST 2018
     */
    private Integer transId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_flow01.status
     *
     * @mbg.generated Mon Nov 05 16:16:19 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_flow01.txn
     *
     * @mbg.generated Mon Nov 05 16:16:19 CST 2018
     */
    private Long txn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_flow01.bill_number
     *
     * @mbg.generated Mon Nov 05 16:16:19 CST 2018
     */
    private Integer billNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_flow01.usr_id
     *
     * @mbg.generated Mon Nov 05 16:16:19 CST 2018
     */
    private Integer usrId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_flow01.trans_id
     *
     * @return the value of trans_flow01.trans_id
     *
     * @mbg.generated Mon Nov 05 16:16:19 CST 2018
     */
    public Integer getTransId() {
        return transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_flow01.trans_id
     *
     * @param transId the value for trans_flow01.trans_id
     *
     * @mbg.generated Mon Nov 05 16:16:19 CST 2018
     */
    public void setTransId(Integer transId) {
        this.transId = transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_flow01.status
     *
     * @return the value of trans_flow01.status
     *
     * @mbg.generated Mon Nov 05 16:16:19 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_flow01.status
     *
     * @param status the value for trans_flow01.status
     *
     * @mbg.generated Mon Nov 05 16:16:19 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_flow01.txn
     *
     * @return the value of trans_flow01.txn
     *
     * @mbg.generated Mon Nov 05 16:16:19 CST 2018
     */
    public Long getTxn() {
        return txn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_flow01.txn
     *
     * @param txn the value for trans_flow01.txn
     *
     * @mbg.generated Mon Nov 05 16:16:19 CST 2018
     */
    public void setTxn(Long txn) {
        this.txn = txn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_flow01.bill_number
     *
     * @return the value of trans_flow01.bill_number
     *
     * @mbg.generated Mon Nov 05 16:16:19 CST 2018
     */
    public Integer getBillNumber() {
        return billNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_flow01.bill_number
     *
     * @param billNumber the value for trans_flow01.bill_number
     *
     * @mbg.generated Mon Nov 05 16:16:19 CST 2018
     */
    public void setBillNumber(Integer billNumber) {
        this.billNumber = billNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_flow01.usr_id
     *
     * @return the value of trans_flow01.usr_id
     *
     * @mbg.generated Mon Nov 05 16:16:19 CST 2018
     */
    public Integer getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_flow01.usr_id
     *
     * @param usrId the value for trans_flow01.usr_id
     *
     * @mbg.generated Mon Nov 05 16:16:19 CST 2018
     */
    public void setUsrId(Integer usrId) {

        this.usrId = usrId;
    }

    @Override
    public String toString() {
        return "TransFlow{" +
                "transId=" + transId +
                ", status='" + status + '\'' +
                ", txn=" + txn +
                ", billNumber=" + billNumber +
                ", usrId=" + usrId +
                '}';
    }
}